### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by ahlifei** [vc5/JD-Coin#7]
2018-02-28 11:43:45,201 JD-Coin INFO: 使用配置文件 "config.ini".
Traceback (most recent call last):
  File "/home/lf/Codes/vc5/JD-Coin/app/main.py", line 13, in <module>
    from config import users
  File "/home/lf/Codes/vc5/JD-Coin/app/config.py", line 107, in <module>
    users = get_users()
  File "/home/lf/Codes/vc5/JD-Coin/app/config.py", line 97, in get_users
    config = load_config()
  File "/home/lf/Codes/vc5/JD-Coin/app/config.py", line 83, in load_config
    config.read(config_file, encoding=support_encoding_list[0])
  File "/usr/lib/python3.5/configparser.py", line 693, in read
    for filename in filenames:
TypeError: 'PosixPath' object is not iterable

**Comment by vc5** [comment]
先尝试升级到Python3.6，后面我会修复兼容3.5

**Comment by ahlifei** [comment]
谢谢!换成３.6 ok!
